// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSureHi.Data;

#nullable disable

namespace eSureHi.Migrations
{
    [DbContext(typeof(eSureHiDbContext))]
    [Migration("20260330220115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("eSureHi.Models.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logged_at");

                    b.Property<string>("NewValues")
                        .HasColumnType("json")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("json")
                        .HasColumnName("old_values");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext")
                        .HasColumnName("table_name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LogId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("eSureHi.Models.Beneficiary", b =>
                {
                    b.Property<int>("BenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ben_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_primary");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Relationship")
                        .HasColumnType("longtext")
                        .HasColumnName("relationship");

                    b.HasKey("BenId");

                    b.HasIndex("EmpId");

                    b.ToTable("beneficiaries");
                });

            modelBuilder.Entity("eSureHi.Models.BeneficiaryStaging", b =>
                {
                    b.Property<long>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("staging_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("StagingId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Age")
                        .HasColumnType("longtext")
                        .HasColumnName("age");

                    b.Property<string>("BeneficiaryId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("beneficiary_id");

                    b.Property<string>("CauseOfDisability")
                        .HasColumnType("longtext")
                        .HasColumnName("cause_of_disability");

                    b.Property<string>("CivilRegistryId")
                        .HasColumnType("longtext")
                        .HasColumnName("civilregistry_id");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("longtext")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisabilityType")
                        .HasColumnType("longtext")
                        .HasColumnName("disability_type");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsPwd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_pwd");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_senior");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("link_status");

                    b.Property<int?>("LinkedBenId")
                        .HasColumnType("int")
                        .HasColumnName("linked_ben_id");

                    b.Property<int?>("LinkedEmpId")
                        .HasColumnType("int")
                        .HasColumnName("linked_emp_id");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("marital_status");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("middle_name");

                    b.Property<string>("PwdIdNo")
                        .HasColumnType("longtext")
                        .HasColumnName("pwd_id_no");

                    b.Property<long?>("ResidentsId")
                        .HasColumnType("bigint")
                        .HasColumnName("residents_id");

                    b.Property<string>("SeniorIdNo")
                        .HasColumnType("longtext")
                        .HasColumnName("senior_id_no");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext")
                        .HasColumnName("sex");

                    b.HasKey("StagingId");

                    b.ToTable("beneficiary_staging");
                });

            modelBuilder.Entity("eSureHi.Models.Benefit", b =>
                {
                    b.Property<int>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("benefit_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BenefitId"));

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("benefit_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EpId")
                        .HasColumnType("int")
                        .HasColumnName("ep_id");

                    b.Property<DateOnly?>("LastUsedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_used_date");

                    b.Property<decimal>("MaxBenefit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("max_benefit");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<decimal>("Remaining")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("remaining");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("UsedBenefit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("used_benefit");

                    b.Property<int?>("YearPeriod")
                        .HasColumnType("int")
                        .HasColumnName("year_period");

                    b.HasKey("BenefitId");

                    b.HasIndex("EpId");

                    b.ToTable("benefits");
                });

            modelBuilder.Entity("eSureHi.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<decimal>("AmountApproved")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount_approved");

                    b.Property<decimal>("AmountClaimed")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount_claimed");

                    b.Property<decimal>("AmountReleased")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount_released");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_date");

                    b.Property<string>("AttendingPhysician")
                        .HasColumnType("longtext")
                        .HasColumnName("attending_physician");

                    b.Property<int?>("BenId")
                        .HasColumnType("int")
                        .HasColumnName("ben_id");

                    b.Property<DateOnly?>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<string>("ClaimNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("claim_no");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("claim_status");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("HospitalClinic")
                        .HasColumnType("longtext")
                        .HasColumnName("hospital_clinic");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("incident_description");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("ReleasedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("released_date");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_date");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ClaimId");

                    b.HasIndex("BenId");

                    b.HasIndex("EmpId");

                    b.HasIndex("PolicyId");

                    b.ToTable("claims");
                });

            modelBuilder.Entity("eSureHi.Models.ClaimDocument", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doc_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("doc_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("int")
                        .HasColumnName("file_size_kb");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DocId");

                    b.HasIndex("ClaimId");

                    b.ToTable("claim_documents");
                });

            modelBuilder.Entity("eSureHi.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dept_code");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("DeptId");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("eSureHi.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DocTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("doc_title");

                    b.Property<int>("DocTypeId")
                        .HasColumnType("int")
                        .HasColumnName("doc_type_id");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<string>("FileSize")
                        .HasColumnType("longtext")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocTypeId");

                    b.HasIndex("EmpId");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("eSureHi.Models.DocumentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("priority");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processed_by");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subject");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_no");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("document_transactions");
                });

            modelBuilder.Entity("eSureHi.Models.DocumentType", b =>
                {
                    b.Property<int>("DocTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("doc_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type_name");

                    b.HasKey("DocTypeId");

                    b.ToTable("document_types");
                });

            modelBuilder.Entity("eSureHi.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext")
                        .HasColumnName("address_line2");

                    b.Property<string>("City")
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("civil_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateHired")
                        .HasColumnType("date")
                        .HasColumnName("date_hired");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateOnly?>("DateSeparated")
                        .HasColumnType("date")
                        .HasColumnName("date_separated");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_no");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employment_status");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employment_type");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext")
                        .HasColumnName("middle_name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nationality");

                    b.Property<string>("PhoneMobile")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_mobile");

                    b.Property<string>("PhoneOffice")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_office");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext")
                        .HasColumnName("photo_path");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("position_title");

                    b.Property<string>("Province")
                        .HasColumnType("longtext")
                        .HasColumnName("province");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext")
                        .HasColumnName("suffix");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext")
                        .HasColumnName("zip_code");

                    b.HasKey("EmpId");

                    b.HasIndex("DeptId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("eSureHi.Models.EmployeePolicy", b =>
                {
                    b.Property<int>("EpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ep_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EpId"));

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assignment_status");

                    b.Property<decimal>("CoverageLimit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coverage_limit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<decimal>("EmployeeShare")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employee_share");

                    b.Property<decimal>("EmployerShare")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employer_share");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("EpId");

                    b.HasIndex("EmpId");

                    b.HasIndex("PolicyId");

                    b.ToTable("employee_policies");
                });

            modelBuilder.Entity("eSureHi.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coverage_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("policy_code");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("policy_name");

                    b.Property<string>("PolicyStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("policy_status");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("policy_type");

                    b.Property<string>("ProviderContact")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_contact");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_name");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date")
                        .HasColumnName("renewal_date");

                    b.Property<string>("TermsConditions")
                        .HasColumnType("longtext")
                        .HasColumnName("terms_conditions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId");

                    b.ToTable("insurance_policies");
                });

            modelBuilder.Entity("eSureHi.Models.Notification", b =>
                {
                    b.Property<int>("NotifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notif_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotifId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("NotifType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("notif_type");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedTable")
                        .HasColumnType("longtext")
                        .HasColumnName("related_table");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("NotifId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("eSureHi.Models.Premium", b =>
                {
                    b.Property<int>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("premium_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PremiumId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("balance");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal>("EmployeeAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employee_amount");

                    b.Property<decimal>("EmployerAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employer_amount");

                    b.Property<int>("EpId")
                        .HasColumnType("int")
                        .HasColumnName("ep_id");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("late_fee");

                    b.Property<DateOnly?>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("longtext")
                        .HasColumnName("reference_no");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext")
                        .HasColumnName("remarks");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PremiumId");

                    b.HasIndex("EpId");

                    b.ToTable("premiums");
                });

            modelBuilder.Entity("eSureHi.Models.Receiver", b =>
                {
                    b.Property<int>("ReceiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receiver_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReceiverId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("receiver_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("ReceiverId");

                    b.ToTable("receivers");
                });

            modelBuilder.Entity("eSureHi.Models.Sender", b =>
                {
                    b.Property<int>("SenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SenderId"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sender_name");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sender_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("SenderId");

                    b.ToTable("senders");
                });

            modelBuilder.Entity("eSureHi.Models.SystemUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("EmpId");

                    b.ToTable("system_users");
                });

            modelBuilder.Entity("eSureHi.Models.VwClaimsSummary", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int>("ApprovedClaims")
                        .HasColumnType("int")
                        .HasColumnName("approved_claims");

                    b.Property<string>("DeptName")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_no");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<int>("PendingClaims")
                        .HasColumnType("int")
                        .HasColumnName("pending_claims");

                    b.Property<int>("RejectedClaims")
                        .HasColumnType("int")
                        .HasColumnName("rejected_claims");

                    b.Property<decimal>("TotalApproved")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_approved");

                    b.Property<decimal>("TotalClaimed")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_claimed");

                    b.Property<int>("TotalClaims")
                        .HasColumnType("int")
                        .HasColumnName("total_claims");

                    b.Property<decimal>("TotalReleased")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_released");

                    b.HasKey("EmpId");

                    b.ToTable("vw_claims_summary");

                    b.ToView("vw_claims_summary", (string)null);
                });

            modelBuilder.Entity("eSureHi.Models.VwEmployeeCoverage", b =>
                {
                    b.Property<int>("EpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ep_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EpId"));

                    b.Property<string>("AssignmentStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("assignment_status");

                    b.Property<decimal>("CoverageLimit")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coverage_limit");

                    b.Property<string>("DeptName")
                        .HasColumnType("longtext")
                        .HasColumnName("dept_name");

                    b.Property<int>("EmpId")
                        .HasColumnType("int")
                        .HasColumnName("emp_id");

                    b.Property<string>("EmployeeNo")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_no");

                    b.Property<decimal>("EmployeeShare")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employee_share");

                    b.Property<decimal>("EmployerShare")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("employer_share");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("PolicyName")
                        .HasColumnType("longtext")
                        .HasColumnName("policy_name");

                    b.Property<string>("PolicyType")
                        .HasColumnType("longtext")
                        .HasColumnName("policy_type");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("EpId");

                    b.ToTable("vw_employee_coverage");

                    b.ToView("vw_employee_coverage", (string)null);
                });

            modelBuilder.Entity("eSureHi.Models.VwPremiumStatus", b =>
                {
                    b.Property<int>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("premium_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PremiumId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("amount_paid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("balance");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("longtext")
                        .HasColumnName("employee_name");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<string>("PolicyName")
                        .HasColumnType("longtext")
                        .HasColumnName("policy_name");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.HasKey("PremiumId");

                    b.ToTable("vw_premium_status");

                    b.ToView("vw_premium_status", (string)null);
                });

            modelBuilder.Entity("eSureHi.Models.Beneficiary", b =>
                {
                    b.HasOne("eSureHi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("eSureHi.Models.Benefit", b =>
                {
                    b.HasOne("eSureHi.Models.EmployeePolicy", "EmployeePolicy")
                        .WithMany()
                        .HasForeignKey("EpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePolicy");
                });

            modelBuilder.Entity("eSureHi.Models.Claim", b =>
                {
                    b.HasOne("eSureHi.Models.Beneficiary", "Beneficiary")
                        .WithMany()
                        .HasForeignKey("BenId");

                    b.HasOne("eSureHi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSureHi.Models.InsurancePolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("eSureHi.Models.ClaimDocument", b =>
                {
                    b.HasOne("eSureHi.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("eSureHi.Models.Document", b =>
                {
                    b.HasOne("eSureHi.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSureHi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("eSureHi.Models.DocumentTransaction", b =>
                {
                    b.HasOne("eSureHi.Models.Receiver", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("eSureHi.Models.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("eSureHi.Models.Employee", b =>
                {
                    b.HasOne("eSureHi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("eSureHi.Models.EmployeePolicy", b =>
                {
                    b.HasOne("eSureHi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSureHi.Models.InsurancePolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("eSureHi.Models.Premium", b =>
                {
                    b.HasOne("eSureHi.Models.EmployeePolicy", "EmployeePolicy")
                        .WithMany()
                        .HasForeignKey("EpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePolicy");
                });

            modelBuilder.Entity("eSureHi.Models.SystemUser", b =>
                {
                    b.HasOne("eSureHi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmpId");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
